import {cpSync, mkdtempSync, readFileSync, rmSync, writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';
import {afterEach, describe, expect, it} from 'vitest';

import {checkDesignAssets} from '../../../02_proceso/workflows/trainer-os/check-design-assets.ts';
import {
  TrainerArtifactProfilesSchema,
  TrainerAssetRightsSchema,
  TrainerMicrocopySchema,
} from '../../../02_proceso/workflows/trainer-os/design-assets.schemas.ts';

const root = process.cwd();
const temporary: string[] = [];
const read = (name: string): unknown =>
  JSON.parse(readFileSync(resolve(root, '03_artefactos/projects/trainer-os/design', name), 'utf8'));
afterEach(() => {
  for (const path of temporary.splice(0)) rmSync(path, {recursive: true, force: true});
});

describe('trainer design candidate assets', () => {
  it('passes the material checker and deterministic projections', async () => {
    expect(await checkDesignAssets(root)).toEqual([]);
  });
  it('rejects malformed rights, profiles and locale contracts', () => {
    const rights = read('assets-rights.json') as Record<string, unknown>;
    expect(
      TrainerAssetRightsSchema.safeParse({...rights, publicationAuthority: true}).success,
    ).toBe(false);
    const swapped = structuredClone(rights) as {assets: Array<{sha256: string}>};
    const first = swapped.assets[0];
    if (!first) throw new Error('fixture asset missing');
    first.sha256 = swapped.assets[1]?.sha256 ?? '';
    expect(TrainerAssetRightsSchema.safeParse(swapped).success).toBe(false);
    const profiles = read('artifact-profiles.json') as {profiles: Array<Record<string, unknown>>};
    const changed = structuredClone(profiles);
    changed.profiles[0] = {...changed.profiles[0], sectionCount: 7};
    expect(TrainerArtifactProfilesSchema.safeParse(changed).success).toBe(false);
    const microcopy = read('microcopy.json') as {locales: {pt: {open: string}}};
    microcopy.locales.pt.open = '';
    expect(TrainerMicrocopySchema.safeParse(microcopy).success).toBe(false);
  });
  it('detects a mutated generated byte', async () => {
    const sandbox = mkdtempSync(resolve(tmpdir(), 'trainer-design-'));
    temporary.push(sandbox);
    cpSync(resolve(root, '03_artefactos'), resolve(sandbox, '03_artefactos'), {recursive: true});
    const projection = resolve(sandbox, '03_artefactos/projects/trainer-os/design/tokens.json');
    writeFileSync(projection, `${readFileSync(projection, 'utf8')} `, 'utf8');
    expect(await checkDesignAssets(sandbox)).toContain('TRAINER_PROJECTION_DRIFT:tokens.json');
  });
});
