#!/usr/bin/env node
import {execFileSync, spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {mkdtempSync, mkdirSync, readFileSync, realpathSync, rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';

import Ajv2020 from 'ajv/dist/2020.js';

import {detectSensitiveSignals} from '../../content-os-sensitive-signal-detector/scripts/detect-sensitive-signals.mjs';
import {executeMinimalRedaction} from '../../content-os-minimal-redaction/scripts/execute-minimal-redaction.mjs';
import {assertDisclosureCurtain, assertPublicationPrivacyReport, disclosureLinesFor, verifyPublicationPrivacy} from './verify-publication-privacy.mjs';

const sha = (value) => createHash('sha256').update(value).digest('hex');
const stable = (value) => Array.isArray(value) ? value.map(stable) : value && typeof value === 'object' ? Object.fromEntries(Object.keys(value).sort().map((key) => [key, stable(value[key])])) : value;
const digest = (value) => sha(JSON.stringify(stable(value)));
const seal = (value) => ({...value, canonical_sha256: digest(value)});
const physical = (ref, value) => { const bytes = Buffer.from(JSON.stringify(stable(value))); return {ref, sha256: sha(bytes), bytes: bytes.length, content_base64: bytes.toString('base64')}; };
const clone = (value) => structuredClone(value);
const blocked = (name, operation, code) => { try { operation(); } catch (error) { if (String(error.message).includes(code)) return; throw new Error(`${name}:${error.message}`); } throw new Error(`${name}:accepted`); };
const command = (tool, args) => { const result = spawnSync(tool, args, {encoding: 'utf8', maxBuffer: 32 * 1024 * 1024}); if (result.status !== 0) throw new Error(`COMMAND:${result.stderr}`); };
const fileAuthority = (path, prefix) => { const bytes = readFileSync(path); return {[`${prefix}_path`]: path, [`${prefix}_sha256`]: sha(bytes), [`${prefix}_bytes`]: bytes.length}; };
const metadata = {frame_width: 320, frame_height: 180, frame_count: 60, duration_ms: 2000, has_audio: true};
const aliases = [{alias_id: 'ALIAS-GNP', kind: 'BRAND_TEXT', canonical: 'GNP', variants: ['G.N.P.']}];
const template = (template_id, kind, identity) => { const bytes = Buffer.from(identity); return {template_id, kind, identity, content_base64: bytes.toString('base64'), sha256: sha(bytes), bytes: bytes.length}; };
const templates = [template('TPL-SOFKA', 'LOGO', 'Sofka'), template('TPL-GNP', 'LOGO', 'GNP'), template('TPL-METODOLOGIA', 'LOGO', 'MetodologIA')];
const evidenceActors = {OCR_TSV: 'RT-09-PRIVACY-OCR-VERIFIER', TEMPLATE: 'RT-09-PRIVACY-TEMPLATE-VERIFIER', FACE_MANUAL: 'RT-11-PRIVACY-GUARDIAN', AUDIO_TRANSCRIPT: 'RT-09-PRIVACY-AUDIO-VERIFIER'};

const detectorRequest = (source, suffix, observations) => {
  const sourceMetadataSha256 = digest(metadata);
  const sourceProbe = {schema_version: 'sensitive-signal-source-probe-v1', actor_id: 'RT-09-PRIVACY-SOURCE-PROBE-VERIFIER', case_id: 'CASE-PUBLICATION', source_sha256: source.sha256, source_bytes: source.bytes, source_metadata_sha256: sourceMetadataSha256, source_metadata: metadata};
  const coverage = {visual_text: 'COMPLETE', visual_templates: 'COMPLETE', faces: 'COMPLETE', audio_transcript: 'COMPLETE'};
  const coverageReceipt = {schema_version: 'sensitive-signal-coverage-receipt-v1', actor_id: 'RT-09-PRIVACY-COVERAGE-VERIFIER', case_id: 'CASE-PUBLICATION', source_sha256: source.sha256, source_metadata_sha256: sourceMetadataSha256, coverage};
  const bound = observations.map((observation) => { const semantic = Object.fromEntries(Object.entries(observation).filter(([key]) => key !== 'observation_id')); const receipt = {schema_version: 'sensitive-signal-observation-evidence-v1', actor_id: evidenceActors[observation.modality], case_id: 'CASE-PUBLICATION', source_sha256: source.sha256, source_metadata_sha256: sourceMetadataSha256, observation_id: observation.observation_id, modality: observation.modality, observation_sha256: digest(semantic)}; return {...observation, evidence: physical(`evidence/${suffix}-${observation.observation_id.toLowerCase()}.json`, receipt)}; });
  return {schema_version: 'sensitive-signal-detector-request-v1', case_id: 'CASE-PUBLICATION', source: {...source, ...metadata}, source_probe_receipt: physical(`receipts/${suffix}-source-probe.json`, sourceProbe), actor_id: 'RT-07-H03-PRIVACY-DETECTOR-PRODUCER', aliases, aliases_sha256: digest(aliases), templates, templates_sha256: digest(templates), coverage, coverage_receipt: physical(`receipts/${suffix}-coverage.json`, coverageReceipt), observations: bound};
};

const observation = (observation_id, modality, fields) => ({observation_id, modality, text: null, template_id: null, identity: null, frame_span: null, time_span_ms: null, geometry: null, confidence: 0.98, ...fields});
const preObservations = [
  observation('OBS-OCR', 'OCR_TSV', {text: 'Resultado visible', frame_span: {start: 0, end: 59}, geometry: {x: 100, y: 45, width: 120, height: 20}}),
  observation('OBS-SOFKA', 'TEMPLATE', {template_id: 'TPL-SOFKA', frame_span: {start: 0, end: 19}, geometry: {x: 10, y: 8, width: 30, height: 10}}),
  observation('OBS-GNP-A', 'TEMPLATE', {template_id: 'TPL-GNP', frame_span: {start: 20, end: 29}, geometry: {x: 10, y: 8, width: 25, height: 10}}),
  observation('OBS-GNP-B', 'TEMPLATE', {template_id: 'TPL-GNP', frame_span: {start: 30, end: 39}, geometry: {x: 50, y: 8, width: 25, height: 10}}),
  observation('OBS-NATALIA', 'FACE_MANUAL', {identity: 'Natalia', frame_span: {start: 0, end: 59}, geometry: {x: 130, y: 50, width: 50, height: 60}}),
  observation('OBS-AUDIO', 'AUDIO_TRANSCRIPT', {text: 'Caso para GNP autorizado', time_span_ms: {start: 600, end: 900}}),
];
const postObservations = [
  observation('OBS-POST-OCR', 'OCR_TSV', {text: 'Resultado visible', frame_span: {start: 0, end: 59}, geometry: {x: 100, y: 45, width: 120, height: 20}}),
  observation('OBS-POST-METODOLOGIA', 'TEMPLATE', {template_id: 'TPL-METODOLOGIA', frame_span: {start: 0, end: 59}, geometry: {x: 5, y: 150, width: 30, height: 10}}),
  observation('OBS-POST-NATALIA', 'FACE_MANUAL', {identity: 'Natalia', frame_span: {start: 0, end: 59}, geometry: {x: 130, y: 50, width: 50, height: 60}}),
  observation('OBS-POST-AUDIO', 'AUDIO_TRANSCRIPT', {text: 'Caso autorizado', time_span_ms: {start: 600, end: 900}}),
];

const root = mkdtempSync(resolve(tmpdir(), 'publication-privacy-check-'));
try {
  const sourceRoot = resolve(root, 'source'); const outputRoot = resolve(root, 'output'); mkdirSync(sourceRoot); mkdirSync(outputRoot);
  const ffmpeg = realpathSync(execFileSync('which', ['ffmpeg'], {encoding: 'utf8'}).trim()); const ffprobe = realpathSync(execFileSync('which', ['ffprobe'], {encoding: 'utf8'}).trim()); const sourcePath = resolve(sourceRoot, 'class-memory.mp4');
  command(ffmpeg, ['-v', 'error', '-f', 'lavfi', '-i', 'testsrc2=size=320x180:rate=30:duration=2', '-f', 'lavfi', '-i', 'aevalsrc=sin(2*PI*880*t)|sin(2*PI*440*t):s=48000:d=2:c=stereo', '-frames:v', '60', '-c:v', 'libx264', '-preset', 'medium', '-crf', '0', '-pix_fmt', 'yuv420p', '-c:a', 'alac', '-movflags', '+faststart', sourcePath]);
  const sourceBytes = readFileSync(sourcePath); const source = {ref: 'class-memory.mp4', sha256: sha(sourceBytes), bytes: sourceBytes.length, content_base64: sourceBytes.toString('base64')};
  const preRequest = detectorRequest(source, 'pre', preObservations); const preInventory = detectSensitiveSignals(preRequest); const preInventoryMaterial = physical('inventories/pre.json', preInventory);
  const sourceRef = {ref: source.ref, sha256: source.sha256, bytes: source.bytes};
  const rules = preInventory.signals.map((signal, sequence) => ({sequence, signal_id: signal.signal_id, kind: signal.kind, identity: signal.identity.canonical, rule: signal.kind === 'SPOKEN_BRAND' ? 'AUDIO_SILENCE' : signal.kind === 'FACE' ? 'KEEP' : 'PROTECT', reason_code: signal.kind === 'FACE' ? 'AUTHORIZED_PARTICIPANT' : 'CLIENT_BRAND', evidence_sha256: signal.evidence.material.sha256}));
  const policy = seal({schema_version: 'privacy-policy-v1', policy_id: 'POLICY:publication', case_id: 'CASE-PUBLICATION', participant_id: 'PARTICIPANT-NATALIA', inventory: {ref: preInventoryMaterial.ref, sha256: preInventoryMaterial.sha256, bytes: preInventoryMaterial.bytes}, planner_actor_id: 'RT-07-H03-PRIVACY-PLANNER-PRODUCER', authorization_actor_id: 'RT-04-PRIVACY-AUTHORIZATION-RECORDER', rules, status: 'BLOCKED_PENDING_VALUE_PRESERVATION_AND_REDACTION_PLAN'});
  const valuePlan = seal({schema_version: 'value-preservation-plan-v1', plan_id: 'VALUE:publication', case_id: 'CASE-PUBLICATION', participant_id: 'PARTICIPANT-NATALIA', source: sourceRef, source_metadata: metadata, privacy_policy_sha256: policy.canonical_sha256, value_guardian_actor_id: 'RT-11-PRIVACY-VALUE-GUARDIAN', zones: [{sequence: 0, zone_id: 'VALUE-STUDENT-WORK', kind: 'STUDENT_DELIVERABLE', frame_span: {start: 0, end: 59}, geometry: {x: 100, y: 45, width: 180, height: 105}, authorized_redaction_signal_ids: []}], status: 'BLOCKED_PENDING_MINIMAL_REDACTION_PLAN'});
  const visualRois = [{effect: {x: 0, y: 0, width: 50, height: 30}}, {effect: {x: 0, y: 0, width: 45, height: 30}}, {effect: {x: 40, y: 0, width: 45, height: 30}}]; let visualIndex = 0;
  const operations = rules.filter(({rule}) => rule !== 'KEEP').map((rule, sequence) => { const signal = preInventory.signals.find(({signal_id}) => signal_id === rule.signal_id); if (rule.rule === 'AUDIO_SILENCE') return {sequence, operation_id: `OP-${sequence}`, signal_id: rule.signal_id, type: 'AUDIO_SILENCE', frame_span: null, time_span_ms: signal.time_span_ms, signal_roi: null, authorized_effect_roi: null, tracking: null, reframe_edge: null, padding_px: null, feather_px: null, fade_ms: 45, subtitle_replacement: '[…]', source_evidence_sha256: rule.evidence_sha256}; const current = visualRois[visualIndex++]; return {sequence, operation_id: `OP-${sequence}`, signal_id: rule.signal_id, type: 'LOCAL_BLUR', frame_span: signal.frame_span, time_span_ms: null, signal_roi: signal.geometry, authorized_effect_roi: current.effect, tracking: 'EXACT_DETECTION_SPAN', reframe_edge: null, padding_px: 4, feather_px: 6, fade_ms: null, subtitle_replacement: null, source_evidence_sha256: rule.evidence_sha256}; });
  const plan = seal({schema_version: 'redaction-plan-v2', plan_id: 'REDACTION:publication', case_id: 'CASE-PUBLICATION', participant_id: 'PARTICIPANT-NATALIA', inventory_sha256: preInventoryMaterial.sha256, privacy_policy_sha256: policy.canonical_sha256, value_preservation_plan_sha256: valuePlan.canonical_sha256, operations, mask_budget: {review_target_ratio: 0.05, hard_limit_ratio: 0.1, max_planned_ratio: 0.02604167, requires_review: false}, status: 'BLOCKED_PENDING_MINIMAL_REDACTION_EXECUTOR'});
  const audioRule = rules.find(({rule}) => rule === 'AUDIO_SILENCE'); const caption = seal({schema_version: 'privacy-caption-track-v1', actor_id: 'RT-07-H03-CAPTION-TRACK-PRODUCER', case_id: 'CASE-PUBLICATION', source_sha256: source.sha256, language: 'es-CO', cues: [{sequence: 0, cue_id: 'CUE-1', start_ms: 500, end_ms: 1000, text: 'Caso para GNP autorizado', signal_spans: [{signal_id: audioRule.signal_id, start_char: 10, end_char: 13}]}]});
  const policyMaterial = physical('plans/privacy-policy.json', policy); const valueMaterial = physical('plans/value-plan.json', valuePlan); const planMaterial = physical('plans/redaction-plan.json', plan); const captionMaterial = physical('captions/source.json', caption);
  const planReceipt = {schema_version: 'contextual-privacy-plan-verification-v1', actor_id: 'RT-09-H03-CONTEXTUAL-PRIVACY-PLAN-VERIFIER', case_id: 'CASE-PUBLICATION', participant_id: 'PARTICIPANT-NATALIA', privacy_policy_material_sha256: policyMaterial.sha256, privacy_policy_canonical_sha256: policy.canonical_sha256, value_preservation_plan_material_sha256: valueMaterial.sha256, value_preservation_plan_canonical_sha256: valuePlan.canonical_sha256, redaction_plan_material_sha256: planMaterial.sha256, redaction_plan_canonical_sha256: plan.canonical_sha256, source: sourceRef, status: 'VERIFIED_MINIMAL_REDACTION_ELIGIBLE'};
  const captionReceipt = {schema_version: 'privacy-caption-track-verification-v1', actor_id: 'RT-09-H03-CAPTION-TRACK-VERIFIER', case_id: 'CASE-PUBLICATION', source: sourceRef, caption_track_material_sha256: captionMaterial.sha256, caption_track_canonical_sha256: caption.canonical_sha256, status: 'VERIFIED_FOR_MINIMAL_REDACTION'};
  const executionRequest = {schema_version: 'minimal-redaction-request-v1', case_id: 'CASE-PUBLICATION', participant_id: 'PARTICIPANT-NATALIA', actor_id: 'RT-07-H03-MINIMAL-REDACTION-PRODUCER', source: sourceRef, privacy_policy_material: policyMaterial, value_preservation_plan_material: valueMaterial, redaction_plan_material: planMaterial, plan_verification_receipt: physical('receipts/plan-verification.json', planReceipt), caption_track_material: captionMaterial, caption_verification_receipt: physical('receipts/caption-verification.json', captionReceipt), media_tool_authority: {...fileAuthority(ffmpeg, 'ffmpeg'), ...fileAuthority(ffprobe, 'ffprobe')}, output_ref: 'redacted.mp4', caption_output_ref: 'redacted-captions.json', receipt_ref: 'execution-receipt.json'};
  const executionReceipt = executeMinimalRedaction(executionRequest, {source_root: sourceRoot, output_root: outputRoot}); const outputBytes = readFileSync(resolve(outputRoot, executionReceipt.output.ref)); const output = {ref: executionReceipt.output.ref, sha256: executionReceipt.output.sha256, bytes: executionReceipt.output.bytes, content_base64: outputBytes.toString('base64')};
  const postRequest = detectorRequest(output, 'post', postObservations); const postInventory = detectSensitiveSignals(postRequest);
  const reportId = `REPORT:${digest({case_id: 'CASE-PUBLICATION', execution_id: executionReceipt.execution_id}).slice(0, 24)}`;
  const curtain = (curtain_id, kind, clips = []) => seal({schema_version: 'disclosure-curtain-v2', curtain_id, case_id: 'CASE-PUBLICATION', privacy_report_id: reportId, kind, orientation: 'VERTICAL', text_lines: disclosureLinesFor(true), foreground_rgb: '#FFFFFF', background_rgb: '#000000', contrast_ratio: 21, placement: 'LOWER_SAFE_ZONE_CURTAIN_ONLY', text_height_ratio: 0.024, duration_ms: 2000, persistent_watermark: false, autonomous_clip_ids: clips});
  const baseRequest = {schema_version: 'publication-privacy-verification-request-v1', case_id: 'CASE-PUBLICATION', participant_id: 'PARTICIPANT-NATALIA', actor_id: 'RT-09-H03-PUBLICATION-PRIVACY-VERIFIER', execution_request_material: physical('audit/execution-request.json', executionRequest), execution_receipt_material: physical('audit/execution-receipt.json', executionReceipt), pre_detection: {request_material: physical('audit/pre-request.json', preRequest), inventory_material: preInventoryMaterial}, post_detection: {request_material: physical('audit/post-request.json', postRequest), inventory_material: physical('inventories/post.json', postInventory)}, disclosure_curtains: [curtain('CURTAIN-INTRO', 'INTRO', ['CLIP-REEL']), curtain('CURTAIN-CHAPTER', 'CHAPTER'), curtain('CURTAIN-OUTRO', 'OUTRO')], autonomous_clips: [{sequence: 0, clip_id: 'CLIP-REEL', curtain_ids: ['CURTAIN-INTRO']}]};
  const evidence = {source_root: sourceRoot, output_root: outputRoot}; const report = verifyPublicationPrivacy(baseRequest, evidence); assertPublicationPrivacyReport(report, baseRequest, evidence);
  const reportSchema = JSON.parse(readFileSync('03_artefactos/skills/content-os-publication-privacy-verifier/schemas/publication-privacy-report-v1.schema.json', 'utf8')); const curtainSchema = JSON.parse(readFileSync('03_artefactos/skills/content-os-general-video/schemas/disclosure-curtain-v2.schema.json', 'utf8')); const ajv = new Ajv2020({strict: true}); const validateReport = ajv.compile(reportSchema); const validateCurtain = ajv.compile(curtainSchema);
  if (!validateReport(report) || baseRequest.disclosure_curtains.some((item) => !validateCurtain(item))) throw new Error(`PUBLICATION-SCHEMA:${JSON.stringify(validateReport.errors ?? validateCurtain.errors)}`);
  if (report.status !== 'VERIFIED_FOR_HUMAN_PLAYBACK' || report.maximum_state !== 'RENDERED_DRAFT' || report.publication_authority !== false || report.residuals.length || report.visual_integrity.outside_mask_rgb_mismatch_frames.length || !report.visual_integrity.zero_unexplained_pixels || report.value_preservation.occlusions.length || report.audio_integrity.outside_span_changed_samples || report.audio_integrity.silences.some(({center_silent}) => !center_silent) || report.disclosure.curtain_findings.length || report.disclosure.clips_without_curtain.length || report.disclosure.state !== 'AI_EDITED_AND_CLASS_MEMORY_AUTHORIZED') throw new Error('PUBLICATION-GOOD-REPORT');
  if (JSON.stringify(disclosureLinesFor(false)) !== JSON.stringify(['EDITADO CON IA']) || JSON.stringify(disclosureLinesFor(true)) !== JSON.stringify(['EDITADO CON IA', 'MEMORIA DE CLASE AUTORIZADA'])) throw new Error('PUBLICATION-DISCLOSURE-CONDITION');
  blocked('extra-request-field', () => verifyPublicationPrivacy({...baseRequest, publish: true}, evidence), 'PUBLICATION-REQUEST-KEYS'); blocked('root-reuse', () => verifyPublicationPrivacy(baseRequest, {source_root: sourceRoot, output_root: sourceRoot}), 'PUBLICATION-ROOT-REUSE');
  const badHashCurtain = clone(baseRequest.disclosure_curtains[0]); badHashCurtain.canonical_sha256 = '0'.repeat(64); blocked('curtain-hash', () => assertDisclosureCurtain(badHashCurtain), 'DISCLOSURE-CURTAIN-HASH');
  const promoted = {...report, maximum_state: 'READY'}; blocked('report-promotion', () => assertPublicationPrivacyReport(promoted, baseRequest, evidence), 'PUBLICATION-REPORT-STATE'); blocked('report-extra-field', () => assertPublicationPrivacyReport({...report, publish: true}, baseRequest, evidence), 'PUBLICATION-REPORT-KEYS');
  const blockedRequest = clone(baseRequest); const residualPost = detectorRequest(output, 'residual', postObservations.map((item) => item.observation_id === 'OBS-POST-AUDIO' ? {...item, text: 'Caso GNP'} : item)); const residualInventory = detectSensitiveSignals(residualPost); blockedRequest.post_detection = {request_material: physical('audit/residual-request.json', residualPost), inventory_material: physical('inventories/residual.json', residualInventory)}; blockedRequest.disclosure_curtains[0].foreground_rgb = '#777777'; blockedRequest.disclosure_curtains[0].background_rgb = '#777777'; blockedRequest.disclosure_curtains[0].contrast_ratio = 1; blockedRequest.disclosure_curtains[0].canonical_sha256 = digest(Object.fromEntries(Object.entries(blockedRequest.disclosure_curtains[0]).filter(([key]) => key !== 'canonical_sha256'))); blockedRequest.autonomous_clips[0].curtain_ids = [];
  const blockedReport = verifyPublicationPrivacy(blockedRequest, evidence); if (blockedReport.status !== 'BLOCKED_PRIVACY_FINDINGS' || blockedReport.residuals.length !== 1 || !blockedReport.disclosure.curtain_findings.some(({code}) => code === 'CONTRAST') || !blockedReport.disclosure.clips_without_curtain.includes('CLIP-REEL')) throw new Error('PUBLICATION-BLOCKED-REPORT');
  const forgedReceiptRequest = clone(baseRequest); const forgedReceipt = JSON.parse(Buffer.from(forgedReceiptRequest.execution_receipt_material.content_base64, 'base64').toString('utf8')); forgedReceipt.actor_id = baseRequest.actor_id; forgedReceiptRequest.execution_receipt_material = physical('audit/forged-receipt.json', forgedReceipt); blocked('forged-executor-receipt', () => verifyPublicationPrivacy(forgedReceiptRequest, evidence), 'MINIMAL-EXECUTION-STATE');
  console.info(`PASS publication-privacy-verifier: ${report.visual_integrity.compared_frames} RGB frames, ${report.audio_integrity.silences.length} exact silence, 3 disclosed curtains and 8 fail-closed gates.`);
} finally { rmSync(root, {recursive: true, force: true}); }
