export const SOURCE_AUTHORITY_RECEIPT_CODES = {
  alias: 'EXPERIENCE-SOURCE-AUTHORITY-RECEIPT-ALIAS',
  bindingDrift: 'EXPERIENCE-SOURCE-AUTHORITY-RECEIPT-BINDING-DRIFT',
  canonicalDrift: 'EXPERIENCE-SOURCE-AUTHORITY-RECEIPT-CANONICAL-DRIFT',
  duplicate: 'EXPERIENCE-SOURCE-AUTHORITY-RECEIPT-DUPLICATE',
  hashDrift: 'EXPERIENCE-SOURCE-AUTHORITY-RECEIPT-HASH-DRIFT',
  identityInvalid: 'EXPERIENCE-SOURCE-AUTHORITY-RECEIPT-IDENTITY-INVALID',
  invalid: 'EXPERIENCE-SOURCE-AUTHORITY-RECEIPT-INVALID',
  required: 'EXPERIENCE-SOURCE-AUTHORITY-RECEIPT-REQUIRED',
  scopeInvalid: 'EXPERIENCE-SOURCE-AUTHORITY-RECEIPT-SCOPE-INVALID',
} as const;
