#!/usr/bin/env node
import {execFileSync, spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {copyFileSync, lstatSync, mkdtempSync, mkdirSync, readFileSync, realpathSync, rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';

import {assertMinimalRedactionExecution, assertMinimalRedactionRequest, executeMinimalRedaction} from './execute-minimal-redaction.mjs';

const sha = (value) => createHash('sha256').update(value).digest('hex');
const stable = (value) => Array.isArray(value) ? value.map(stable) : value && typeof value === 'object' ? Object.fromEntries(Object.keys(value).sort().map((key) => [key, stable(value[key])])) : value;
const digest = (value) => sha(JSON.stringify(stable(value)));
const seal = (value) => ({...value, canonical_sha256: digest(value)});
const physical = (ref, value) => { const bytes = Buffer.from(JSON.stringify(stable(value))); return {ref, sha256: sha(bytes), bytes: bytes.length, content_base64: bytes.toString('base64')}; };
const hashFile = (path) => { const bytes = readFileSync(path); return {sha256: sha(bytes), bytes: bytes.length}; };
const clone = (value) => structuredClone(value);
const blocked = (name, operation, code) => { try { operation(); } catch (error) { if (String(error.message).includes(code)) return; throw new Error(`${name}:${error.message}`); } throw new Error(`${name}:accepted`); };
const command = (path, args, options = {}) => { const result = spawnSync(path, args, {encoding: Object.hasOwn(options, 'encoding') ? options.encoding : 'utf8', maxBuffer: 32 * 1024 * 1024}); if (result.status !== 0) throw new Error(`COMMAND:${result.stderr}`); return result.stdout; };
const rawFrame = (ffmpeg, path, frame) => command(ffmpeg, ['-v', 'error', '-i', path, '-vf', `select=eq(n\\,${frame})`, '-fps_mode', 'vfr', '-frames:v', '1', '-f', 'rawvideo', '-pix_fmt', 'rgb24', '-'], {encoding: null});
const pcm = (ffmpeg, path) => command(ffmpeg, ['-v', 'error', '-i', path, '-map', '0:a:0', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '48000', '-'], {encoding: null});
const changed = (left, right, width, roi) => { let count = 0; for (let y = roi.y; y < roi.y + roi.height; y += 1) for (let x = roi.x; x < roi.x + roi.width; x += 1) { const offset = (y * width + x) * 3; if (!left.subarray(offset, offset + 3).equals(right.subarray(offset, offset + 3))) count += 1; } return count; };

const root = mkdtempSync(resolve(tmpdir(), 'minimal-redaction-check-'));
try {
  const sourceRoot = resolve(root, 'source'); const outputRoot = resolve(root, 'output'); mkdirSync(sourceRoot); mkdirSync(outputRoot);
  const ffmpeg = realpathSync(execFileSync('which', ['ffmpeg'], {encoding: 'utf8'}).trim()); const ffprobe = realpathSync(execFileSync('which', ['ffprobe'], {encoding: 'utf8'}).trim()); const sourcePath = resolve(sourceRoot, 'class-memory.mp4');
  command(ffmpeg, ['-v', 'error', '-f', 'lavfi', '-i', 'testsrc2=size=320x180:rate=30:duration=2', '-f', 'lavfi', '-i', 'sine=frequency=880:sample_rate=48000:duration=2', '-frames:v', '60', '-c:v', 'libx264', '-preset', 'medium', '-crf', '0', '-pix_fmt', 'yuv420p', '-c:a', 'alac', '-movflags', '+faststart', sourcePath]);
  const sourceBytes = readFileSync(sourcePath); const source = {ref: 'class-memory.mp4', sha256: sha(sourceBytes), bytes: sourceBytes.length}; const metadata = {frame_width: 320, frame_height: 180, frame_count: 60, duration_ms: 2000, has_audio: true};
  const rules = [
    ['SIG-STATIC', 'LOGO', 'Sofka', 'PROTECT', 'CLIENT_BRAND'],
    ['SIG-MOVE-A', 'LOGO', 'GNP', 'PROTECT', 'CLIENT_BRAND'],
    ['SIG-MOVE-B', 'LOGO', 'GNP', 'PROTECT', 'CLIENT_BRAND'],
    ['SIG-CHROME', 'TOOL_CHROME', 'Tool chrome', 'PROTECT', 'PRIVATE_LOCATOR'],
    ['SIG-AUDIO', 'SPOKEN_BRAND', 'GNP', 'AUDIO_SILENCE', 'CLIENT_BRAND'],
  ].map(([signal_id, kind, identity, rule, reason_code], sequence) => ({sequence, signal_id, kind, identity, rule, reason_code, evidence_sha256: sha(signal_id)}));
  const policy = seal({schema_version: 'privacy-policy-v1', policy_id: 'POLICY:fixture', case_id: 'CASE-MINIMAL', participant_id: 'PARTICIPANT-NATALIA', inventory: {ref: 'inventory.json', sha256: '1'.repeat(64), bytes: 100}, planner_actor_id: 'RT-07-H03-PRIVACY-PLANNER-PRODUCER', authorization_actor_id: 'RT-04-PRIVACY-AUTHORIZATION-RECORDER', rules, status: 'BLOCKED_PENDING_VALUE_PRESERVATION_AND_REDACTION_PLAN'});
  const valuePlan = seal({schema_version: 'value-preservation-plan-v1', plan_id: 'VALUE:fixture', case_id: 'CASE-MINIMAL', participant_id: 'PARTICIPANT-NATALIA', source, source_metadata: metadata, privacy_policy_sha256: policy.canonical_sha256, value_guardian_actor_id: 'RT-11-PRIVACY-VALUE-GUARDIAN', zones: [{sequence: 0, zone_id: 'VALUE-STUDENT-WORK', kind: 'STUDENT_DELIVERABLE', frame_span: {start: 0, end: 59}, geometry: {x: 100, y: 45, width: 180, height: 105}, authorized_redaction_signal_ids: []}], status: 'BLOCKED_PENDING_MINIMAL_REDACTION_PLAN'});
  const visual = (sequence, operation_id, signal_id, frame_span, signal_roi, authorized_effect_roi) => ({sequence, operation_id, signal_id, type: 'LOCAL_BLUR', frame_span, time_span_ms: null, signal_roi, authorized_effect_roi, tracking: 'EXACT_DETECTION_SPAN', reframe_edge: null, padding_px: 4, feather_px: 6, fade_ms: null, subtitle_replacement: null, source_evidence_sha256: sha(signal_id)});
  const operations = [
    visual(0, 'OP-STATIC', 'SIG-STATIC', {start: 0, end: 19}, {x: 10, y: 8, width: 30, height: 10}, {x: 0, y: 0, width: 50, height: 30}),
    visual(1, 'OP-MOVE-A', 'SIG-MOVE-A', {start: 20, end: 29}, {x: 10, y: 8, width: 25, height: 10}, {x: 0, y: 0, width: 45, height: 30}),
    visual(2, 'OP-MOVE-B', 'SIG-MOVE-B', {start: 30, end: 39}, {x: 50, y: 8, width: 25, height: 10}, {x: 40, y: 0, width: 45, height: 30}),
    {sequence: 3, operation_id: 'OP-CHROME', signal_id: 'SIG-CHROME', type: 'REFRAME_PERIPHERAL', frame_span: {start: 50, end: 59}, time_span_ms: null, signal_roi: {x: 20, y: 177, width: 100, height: 3}, authorized_effect_roi: {x: 0, y: 172, width: 320, height: 8}, tracking: 'EXACT_DETECTION_SPAN', reframe_edge: 'BOTTOM', padding_px: 10, feather_px: 0, fade_ms: null, subtitle_replacement: null, source_evidence_sha256: sha('SIG-CHROME')},
    {sequence: 4, operation_id: 'OP-AUDIO', signal_id: 'SIG-AUDIO', type: 'AUDIO_SILENCE', frame_span: null, time_span_ms: {start: 600, end: 900}, signal_roi: null, authorized_effect_roi: null, tracking: null, reframe_edge: null, padding_px: null, feather_px: null, fade_ms: 45, subtitle_replacement: '[…]', source_evidence_sha256: sha('SIG-AUDIO')},
  ];
  const plan = seal({schema_version: 'redaction-plan-v2', plan_id: 'REDACTION:fixture', case_id: 'CASE-MINIMAL', participant_id: 'PARTICIPANT-NATALIA', inventory_sha256: policy.inventory.sha256, privacy_policy_sha256: policy.canonical_sha256, value_preservation_plan_sha256: valuePlan.canonical_sha256, operations, mask_budget: {review_target_ratio: 0.05, hard_limit_ratio: 0.1, max_planned_ratio: 0.04444444, requires_review: false}, status: 'BLOCKED_PENDING_MINIMAL_REDACTION_EXECUTOR'});
  const caption = seal({schema_version: 'privacy-caption-track-v1', case_id: 'CASE-MINIMAL', source_sha256: source.sha256, language: 'es-CO', cues: [{sequence: 0, cue_id: 'CUE-1', start_ms: 500, end_ms: 1000, text: 'Caso para GNP autorizado', signal_spans: [{signal_id: 'SIG-AUDIO', start_char: 10, end_char: 13}]}]});
  const policyMaterial = physical('plans/privacy-policy.json', policy); const valueMaterial = physical('plans/value-plan.json', valuePlan); const planMaterial = physical('plans/redaction-plan.json', plan);
  const verification = {schema_version: 'contextual-privacy-plan-verification-v1', actor_id: 'RT-09-H03-CONTEXTUAL-PRIVACY-PLAN-VERIFIER', case_id: 'CASE-MINIMAL', participant_id: 'PARTICIPANT-NATALIA', privacy_policy_material_sha256: policyMaterial.sha256, privacy_policy_canonical_sha256: policy.canonical_sha256, value_preservation_plan_material_sha256: valueMaterial.sha256, value_preservation_plan_canonical_sha256: valuePlan.canonical_sha256, redaction_plan_material_sha256: planMaterial.sha256, redaction_plan_canonical_sha256: plan.canonical_sha256, source, status: 'VERIFIED_MINIMAL_REDACTION_ELIGIBLE'};
  const request = {schema_version: 'minimal-redaction-request-v1', case_id: 'CASE-MINIMAL', participant_id: 'PARTICIPANT-NATALIA', actor_id: 'RT-07-H03-MINIMAL-REDACTION-PRODUCER', source, privacy_policy_material: policyMaterial, value_preservation_plan_material: valueMaterial, redaction_plan_material: planMaterial, plan_verification_receipt: physical('receipts/plan-verification.json', verification), caption_track_material: physical('captions/source.json', caption), media_tool_authority: {ffmpeg_path: ffmpeg, ...Object.fromEntries(Object.entries(hashFile(ffmpeg)).map(([key, value]) => [`ffmpeg_${key}`, value])), ffprobe_path: ffprobe, ...Object.fromEntries(Object.entries(hashFile(ffprobe)).map(([key, value]) => [`ffprobe_${key}`, value]))}, output_ref: 'redacted.mp4', caption_output_ref: 'redacted-captions.json', receipt_ref: 'execution-receipt.json'};
  assertMinimalRedactionRequest(request); const receipt = executeMinimalRedaction(request, {source_root: sourceRoot, output_root: outputRoot});
  assertMinimalRedactionExecution(receipt, request); if (receipt.maximum_state !== 'RENDERED_DRAFT' || receipt.status !== 'BLOCKED_PENDING_PUBLICATION_PRIVACY_VERIFIER' || receipt.operations.length !== 5 || !lstatSync(resolve(outputRoot, request.receipt_ref)).isFile()) throw new Error('MINIMAL-RECEIPT');
  const outputPath = resolve(outputRoot, request.output_ref); const source45 = rawFrame(ffmpeg, sourcePath, 45); const output45 = rawFrame(ffmpeg, outputPath, 45); if (!source45.equals(output45)) throw new Error('MINIMAL-OUTSIDE-MASK-RGB');
  const source10 = rawFrame(ffmpeg, sourcePath, 10); const output10 = rawFrame(ffmpeg, outputPath, 10); if (changed(source10, output10, 320, {x: 0, y: 0, width: 50, height: 30}) === 0 || changed(source10, output10, 320, {x: 100, y: 45, width: 180, height: 105}) !== 0) throw new Error('MINIMAL-BLUR-LOCALITY');
  const sourceAudio = pcm(ffmpeg, sourcePath); const outputAudio = pcm(ffmpeg, outputPath); const start = 48000 * 2 * 600 / 1000; const end = 48000 * 2 * 900 / 1000; if (!sourceAudio.subarray(0, start).equals(outputAudio.subarray(0, start)) || !sourceAudio.subarray(end).equals(outputAudio.subarray(end))) throw new Error('MINIMAL-AUDIO-OUTSIDE-SPAN'); const middle = outputAudio.subarray(48000 * 2 * 700 / 1000, 48000 * 2 * 800 / 1000); if (middle.some((byte) => byte !== 0)) throw new Error('MINIMAL-AUDIO-NOT-SILENT');
  const captions = JSON.parse(readFileSync(resolve(outputRoot, request.caption_output_ref), 'utf8')); if (captions.cues[0].text !== 'Caso para […] autorizado' || captions.cues[0].replacements.length !== 1) throw new Error('MINIMAL-CAPTION-REPLACEMENT');
  const rebindPlan = (base, mutate) => { const candidate = clone(base); const current = JSON.parse(Buffer.from(candidate.redaction_plan_material.content_base64, 'base64').toString('utf8')); mutate(current); current.canonical_sha256 = digest(Object.fromEntries(Object.entries(current).filter(([key]) => key !== 'canonical_sha256'))); candidate.redaction_plan_material = physical('plans/redaction-plan-mutated.json', current); const verify = JSON.parse(Buffer.from(candidate.plan_verification_receipt.content_base64, 'base64').toString('utf8')); verify.redaction_plan_material_sha256 = candidate.redaction_plan_material.sha256; verify.redaction_plan_canonical_sha256 = current.canonical_sha256; candidate.plan_verification_receipt = physical('receipts/plan-verification-mutated.json', verify); return candidate; };
  blocked('extra-field', () => assertMinimalRedactionRequest({...request, publish: true}), 'MINIMAL-REQUEST-KEYS');
  const stale = clone(request); stale.redaction_plan_material = physical('plans/stale.json', {...plan, plan_id: 'REDACTION:stale', canonical_sha256: digest({...Object.fromEntries(Object.entries(plan).filter(([key]) => key !== 'canonical_sha256')), plan_id: 'REDACTION:stale'})}); blocked('stale-receipt', () => assertMinimalRedactionRequest(stale), 'MINIMAL-VERIFICATION-DRIFT');
  const full = rebindPlan(request, (value) => { value.operations[0].signal_roi = {x: 0, y: 0, width: 320, height: 180}; value.operations[0].authorized_effect_roi = {x: 0, y: 0, width: 320, height: 180}; value.mask_budget.max_planned_ratio = 1; }); blocked('full-frame', () => assertMinimalRedactionRequest(full), 'MINIMAL-MASK-HARD-LIMIT');
  const occlusion = rebindPlan(request, (value) => { value.operations[0].signal_roi = {x: 110, y: 60, width: 10, height: 10}; value.operations[0].authorized_effect_roi = {x: 100, y: 50, width: 30, height: 30}; }); blocked('value-zone', () => assertMinimalRedactionRequest(occlusion), 'MINIMAL-VALUE-ZONE-OCCLUSION');
  const relativeTool = clone(request); relativeTool.media_tool_authority.ffmpeg_path = 'ffmpeg'; blocked('path-tool', () => assertMinimalRedactionRequest(relativeTool), 'MINIMAL-TOOL-AUTHORITY');
  blocked('receipt-promotion', () => assertMinimalRedactionExecution({...receipt, maximum_state: 'READY'}), 'MINIMAL-EXECUTION-STATE');
  blocked('root-reuse', () => executeMinimalRedaction({...request, output_ref: 'other.mp4', caption_output_ref: 'other-captions.json', receipt_ref: 'other-receipt.json'}, {source_root: sourceRoot, output_root: sourceRoot}), 'MINIMAL-ROOT-REUSE'); blocked('overwrite', () => executeMinimalRedaction(request, {source_root: sourceRoot, output_root: outputRoot}), 'MINIMAL-OUTPUT-EXISTS');
  const fake = resolve(root, 'fake-ffmpeg'); copyFileSync(ffmpeg, fake); const fakeTool = clone(request); fakeTool.media_tool_authority.ffmpeg_path = fake; fakeTool.media_tool_authority.ffmpeg_sha256 = '0'.repeat(64); blocked('tool-drift', () => executeMinimalRedaction({...fakeTool, output_ref: 'fake.mp4', caption_output_ref: 'fake-captions.json', receipt_ref: 'fake-receipt.json'}, {source_root: sourceRoot, output_root: outputRoot}), 'VIDEO-OS-CASE-TOOL-UNTRUSTED');
  console.info('PASS minimal-redaction: lossless localized blur, tracked movement, peripheral reframe, exact audio/caption treatment and 9 fail-closed gates.');
} finally { rmSync(root, {recursive: true, force: true}); }
