#!/usr/bin/env node
import {execFileSync, spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {copyFileSync, lstatSync, mkdtempSync, mkdirSync, readFileSync, realpathSync, rmSync, symlinkSync, unlinkSync, writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';

import Ajv2020 from 'ajv/dist/2020.js';

import {assertMinimalRedactionExecution, assertMinimalRedactionRequest, executeMinimalRedaction} from './execute-minimal-redaction.mjs';

const sha = (value) => createHash('sha256').update(value).digest('hex');
const stable = (value) => Array.isArray(value) ? value.map(stable) : value && typeof value === 'object' ? Object.fromEntries(Object.keys(value).sort().map((key) => [key, stable(value[key])])) : value;
const digest = (value) => sha(JSON.stringify(stable(value)));
const seal = (value) => ({...value, canonical_sha256: digest(value)});
const physical = (ref, value) => { const bytes = Buffer.from(JSON.stringify(stable(value))); return {ref, sha256: sha(bytes), bytes: bytes.length, content_base64: bytes.toString('base64')}; };
const hashFile = (path) => { const bytes = readFileSync(path); return {sha256: sha(bytes), bytes: bytes.length}; };
const clone = (value) => structuredClone(value);
const blocked = (name, operation, code) => { try { operation(); } catch (error) { if (String(error.message).includes(code)) return; throw new Error(`${name}:${error.message}`); } throw new Error(`${name}:accepted`); };
const command = (path, args, options = {}) => { const result = spawnSync(path, args, {encoding: Object.hasOwn(options, 'encoding') ? options.encoding : 'utf8', maxBuffer: 32 * 1024 * 1024}); if (result.status !== 0) throw new Error(`COMMAND:${result.stderr}`); return result.stdout; };
const rawFrame = (ffmpeg, path, frame) => command(ffmpeg, ['-v', 'error', '-i', path, '-vf', `select=eq(n\\,${frame})`, '-fps_mode', 'vfr', '-frames:v', '1', '-f', 'rawvideo', '-pix_fmt', 'rgb24', '-'], {encoding: null});
const pcm = (ffmpeg, path) => command(ffmpeg, ['-v', 'error', '-i', path, '-map', '0:a:0', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '2', '-ar', '48000', '-'], {encoding: null});
const changed = (left, right, width, roi) => { let count = 0; for (let y = roi.y; y < roi.y + roi.height; y += 1) for (let x = roi.x; x < roi.x + roi.width; x += 1) { const offset = (y * width + x) * 3; if (!left.subarray(offset, offset + 3).equals(right.subarray(offset, offset + 3))) count += 1; } return count; };

const root = mkdtempSync(resolve(tmpdir(), 'minimal-redaction-check-'));
try {
  const executionSchema = JSON.parse(readFileSync(resolve('03_artefactos/skills/content-os-minimal-redaction/schemas/minimal-redaction-execution-v1.schema.json'), 'utf8')); if (executionSchema.additionalProperties !== false || executionSchema.properties?.maximum_state?.const !== 'RENDERED_DRAFT') throw new Error('MINIMAL-SCHEMA'); const validateExecutionSchema = new Ajv2020({strict: true}).compile(executionSchema);
  const sourceRoot = resolve(root, 'source'); const outputRoot = resolve(root, 'output'); mkdirSync(sourceRoot); mkdirSync(outputRoot);
  const ffmpeg = realpathSync(execFileSync('which', ['ffmpeg'], {encoding: 'utf8'}).trim()); const ffprobe = realpathSync(execFileSync('which', ['ffprobe'], {encoding: 'utf8'}).trim()); const sourcePath = resolve(sourceRoot, 'class-memory.mp4');
  command(ffmpeg, ['-v', 'error', '-f', 'lavfi', '-i', 'testsrc2=size=320x180:rate=30:duration=2', '-f', 'lavfi', '-i', 'aevalsrc=sin(2*PI*880*t)|sin(2*PI*440*t):s=48000:d=2:c=stereo', '-frames:v', '60', '-c:v', 'libx264', '-preset', 'medium', '-crf', '0', '-pix_fmt', 'yuv420p', '-c:a', 'alac', '-movflags', '+faststart', sourcePath]);
  const sourceBytes = readFileSync(sourcePath); const source = {ref: 'class-memory.mp4', sha256: sha(sourceBytes), bytes: sourceBytes.length}; const metadata = {frame_width: 320, frame_height: 180, frame_count: 60, duration_ms: 2000, has_audio: true};
  const rules = [
    ['SIG-STATIC', 'LOGO', 'Sofka', 'PROTECT', 'CLIENT_BRAND'],
    ['SIG-MOVE-A', 'LOGO', 'GNP', 'PROTECT', 'CLIENT_BRAND'],
    ['SIG-MOVE-B', 'LOGO', 'GNP', 'PROTECT', 'CLIENT_BRAND'],
    ['SIG-AUDIO', 'SPOKEN_BRAND', 'GNP', 'AUDIO_SILENCE', 'CLIENT_BRAND'],
  ].map(([signal_id, kind, identity, rule, reason_code], sequence) => ({sequence, signal_id, kind, identity, rule, reason_code, evidence_sha256: sha(signal_id)}));
  const policy = seal({schema_version: 'privacy-policy-v1', policy_id: 'POLICY:fixture', case_id: 'CASE-MINIMAL', participant_id: 'PARTICIPANT-NATALIA', inventory: {ref: 'inventory.json', sha256: '1'.repeat(64), bytes: 100}, planner_actor_id: 'RT-07-H03-PRIVACY-PLANNER-PRODUCER', authorization_actor_id: 'RT-04-PRIVACY-AUTHORIZATION-RECORDER', rules, status: 'BLOCKED_PENDING_VALUE_PRESERVATION_AND_REDACTION_PLAN'});
  const valuePlan = seal({schema_version: 'value-preservation-plan-v1', plan_id: 'VALUE:fixture', case_id: 'CASE-MINIMAL', participant_id: 'PARTICIPANT-NATALIA', source, source_metadata: metadata, privacy_policy_sha256: policy.canonical_sha256, value_guardian_actor_id: 'RT-11-PRIVACY-VALUE-GUARDIAN', zones: [{sequence: 0, zone_id: 'VALUE-STUDENT-WORK', kind: 'STUDENT_DELIVERABLE', frame_span: {start: 0, end: 59}, geometry: {x: 100, y: 45, width: 180, height: 105}, authorized_redaction_signal_ids: []}], status: 'BLOCKED_PENDING_MINIMAL_REDACTION_PLAN'});
  const visual = (sequence, operation_id, signal_id, frame_span, signal_roi, authorized_effect_roi) => ({sequence, operation_id, signal_id, type: 'LOCAL_BLUR', frame_span, time_span_ms: null, signal_roi, authorized_effect_roi, tracking: 'EXACT_DETECTION_SPAN', reframe_edge: null, padding_px: 4, feather_px: 6, fade_ms: null, subtitle_replacement: null, source_evidence_sha256: sha(signal_id)});
  const operations = [
    visual(0, 'OP-STATIC', 'SIG-STATIC', {start: 0, end: 19}, {x: 10, y: 8, width: 30, height: 10}, {x: 0, y: 0, width: 50, height: 30}),
    visual(1, 'OP-MOVE-A', 'SIG-MOVE-A', {start: 20, end: 29}, {x: 10, y: 8, width: 25, height: 10}, {x: 0, y: 0, width: 45, height: 30}),
    visual(2, 'OP-MOVE-B', 'SIG-MOVE-B', {start: 30, end: 39}, {x: 50, y: 8, width: 25, height: 10}, {x: 40, y: 0, width: 45, height: 30}),
    {sequence: 3, operation_id: 'OP-AUDIO', signal_id: 'SIG-AUDIO', type: 'AUDIO_SILENCE', frame_span: null, time_span_ms: {start: 600, end: 900}, signal_roi: null, authorized_effect_roi: null, tracking: null, reframe_edge: null, padding_px: null, feather_px: null, fade_ms: 45, subtitle_replacement: '[…]', source_evidence_sha256: sha('SIG-AUDIO')},
  ];
  const plan = seal({schema_version: 'redaction-plan-v2', plan_id: 'REDACTION:fixture', case_id: 'CASE-MINIMAL', participant_id: 'PARTICIPANT-NATALIA', inventory_sha256: policy.inventory.sha256, privacy_policy_sha256: policy.canonical_sha256, value_preservation_plan_sha256: valuePlan.canonical_sha256, operations, mask_budget: {review_target_ratio: 0.05, hard_limit_ratio: 0.1, max_planned_ratio: 0.02604167, requires_review: false}, status: 'BLOCKED_PENDING_MINIMAL_REDACTION_EXECUTOR'});
  const caption = seal({schema_version: 'privacy-caption-track-v1', actor_id: 'RT-07-H03-CAPTION-TRACK-PRODUCER', case_id: 'CASE-MINIMAL', source_sha256: source.sha256, language: 'es-CO', cues: [{sequence: 0, cue_id: 'CUE-1', start_ms: 500, end_ms: 1000, text: 'Caso para GNP autorizado', signal_spans: [{signal_id: 'SIG-AUDIO', start_char: 10, end_char: 13}]}]});
  const policyMaterial = physical('plans/privacy-policy.json', policy); const valueMaterial = physical('plans/value-plan.json', valuePlan); const planMaterial = physical('plans/redaction-plan.json', plan);
  const verification = {schema_version: 'contextual-privacy-plan-verification-v1', actor_id: 'RT-09-H03-CONTEXTUAL-PRIVACY-PLAN-VERIFIER', case_id: 'CASE-MINIMAL', participant_id: 'PARTICIPANT-NATALIA', privacy_policy_material_sha256: policyMaterial.sha256, privacy_policy_canonical_sha256: policy.canonical_sha256, value_preservation_plan_material_sha256: valueMaterial.sha256, value_preservation_plan_canonical_sha256: valuePlan.canonical_sha256, redaction_plan_material_sha256: planMaterial.sha256, redaction_plan_canonical_sha256: plan.canonical_sha256, source, status: 'VERIFIED_MINIMAL_REDACTION_ELIGIBLE'};
  const captionMaterial = physical('captions/source.json', caption); const captionVerification = {schema_version: 'privacy-caption-track-verification-v1', actor_id: 'RT-09-H03-CAPTION-TRACK-VERIFIER', case_id: 'CASE-MINIMAL', source, caption_track_material_sha256: captionMaterial.sha256, caption_track_canonical_sha256: caption.canonical_sha256, status: 'VERIFIED_FOR_MINIMAL_REDACTION'};
  const request = {schema_version: 'minimal-redaction-request-v1', case_id: 'CASE-MINIMAL', participant_id: 'PARTICIPANT-NATALIA', actor_id: 'RT-07-H03-MINIMAL-REDACTION-PRODUCER', source, privacy_policy_material: policyMaterial, value_preservation_plan_material: valueMaterial, redaction_plan_material: planMaterial, plan_verification_receipt: physical('receipts/plan-verification.json', verification), caption_track_material: captionMaterial, caption_verification_receipt: physical('receipts/caption-verification.json', captionVerification), media_tool_authority: {ffmpeg_path: ffmpeg, ...Object.fromEntries(Object.entries(hashFile(ffmpeg)).map(([key, value]) => [`ffmpeg_${key}`, value])), ffprobe_path: ffprobe, ...Object.fromEntries(Object.entries(hashFile(ffprobe)).map(([key, value]) => [`ffprobe_${key}`, value]))}, output_ref: 'redacted.mp4', caption_output_ref: 'redacted-captions.json', receipt_ref: 'execution-receipt.json'};
  assertMinimalRedactionRequest(request); const receipt = executeMinimalRedaction(request, {source_root: sourceRoot, output_root: outputRoot});
  const executionEvidence = {source_root: sourceRoot, output_root: outputRoot}; assertMinimalRedactionExecution(receipt, request, executionEvidence); if (!validateExecutionSchema(receipt) || receipt.maximum_state !== 'RENDERED_DRAFT' || receipt.status !== 'BLOCKED_PENDING_PUBLICATION_PRIVACY_VERIFIER' || receipt.operations.length !== 4 || !lstatSync(resolve(outputRoot, request.receipt_ref)).isFile()) throw new Error(`MINIMAL-RECEIPT:${JSON.stringify(validateExecutionSchema.errors)}`); const nestedSourceReceipt = clone(receipt); nestedSourceReceipt.source.ref = 'sources/class-memory.mp4'; nestedSourceReceipt.canonical_sha256 = digest(Object.fromEntries(Object.entries(nestedSourceReceipt).filter(([key]) => key !== 'canonical_sha256'))); assertMinimalRedactionExecution(nestedSourceReceipt); if (!validateExecutionSchema(nestedSourceReceipt)) throw new Error(`MINIMAL-SCHEMA-RUNTIME-PARITY:${JSON.stringify(validateExecutionSchema.errors)}`);
  const outputPath = resolve(outputRoot, request.output_ref); const source45 = rawFrame(ffmpeg, sourcePath, 45); const output45 = rawFrame(ffmpeg, outputPath, 45); if (!source45.equals(output45)) throw new Error('MINIMAL-OUTSIDE-MASK-RGB');
  const source10 = rawFrame(ffmpeg, sourcePath, 10); const output10 = rawFrame(ffmpeg, outputPath, 10); if (changed(source10, output10, 320, {x: 0, y: 0, width: 50, height: 30}) === 0 || changed(source10, output10, 320, {x: 100, y: 45, width: 180, height: 105}) !== 0) throw new Error('MINIMAL-BLUR-LOCALITY');
  const sourceAudio = pcm(ffmpeg, sourcePath); const outputAudio = pcm(ffmpeg, outputPath); const start = 48000 * 4 * 600 / 1000; const end = 48000 * 4 * 900 / 1000; if (sourceAudio.length !== outputAudio.length || !sourceAudio.subarray(0, start).equals(outputAudio.subarray(0, start)) || !sourceAudio.subarray(end).equals(outputAudio.subarray(end))) throw new Error('MINIMAL-AUDIO-OUTSIDE-SPAN'); const middle = outputAudio.subarray(48000 * 4 * 700 / 1000, 48000 * 4 * 800 / 1000); if (middle.some((byte) => byte !== 0)) throw new Error('MINIMAL-AUDIO-NOT-SILENT');
  const captions = JSON.parse(readFileSync(resolve(outputRoot, request.caption_output_ref), 'utf8')); if (captions.cues[0].text !== 'Caso para […] autorizado' || captions.cues[0].replacements.length !== 1) throw new Error('MINIMAL-CAPTION-REPLACEMENT');
  const rebindPlan = (base, mutate) => { const candidate = clone(base); const current = JSON.parse(Buffer.from(candidate.redaction_plan_material.content_base64, 'base64').toString('utf8')); mutate(current); current.canonical_sha256 = digest(Object.fromEntries(Object.entries(current).filter(([key]) => key !== 'canonical_sha256'))); candidate.redaction_plan_material = physical('plans/redaction-plan-mutated.json', current); const verify = JSON.parse(Buffer.from(candidate.plan_verification_receipt.content_base64, 'base64').toString('utf8')); verify.redaction_plan_material_sha256 = candidate.redaction_plan_material.sha256; verify.redaction_plan_canonical_sha256 = current.canonical_sha256; candidate.plan_verification_receipt = physical('receipts/plan-verification-mutated.json', verify); return candidate; };
  const rebindSource = (base, reboundSource) => { const candidate = clone(base); candidate.source = reboundSource; const value = JSON.parse(Buffer.from(candidate.value_preservation_plan_material.content_base64, 'base64').toString('utf8')); value.source = reboundSource; value.canonical_sha256 = digest(Object.fromEntries(Object.entries(value).filter(([key]) => key !== 'canonical_sha256'))); candidate.value_preservation_plan_material = physical('plans/value-plan-rebound.json', value); const redaction = JSON.parse(Buffer.from(candidate.redaction_plan_material.content_base64, 'base64').toString('utf8')); redaction.value_preservation_plan_sha256 = value.canonical_sha256; redaction.canonical_sha256 = digest(Object.fromEntries(Object.entries(redaction).filter(([key]) => key !== 'canonical_sha256'))); candidate.redaction_plan_material = physical('plans/redaction-plan-rebound.json', redaction); const verificationReceipt = JSON.parse(Buffer.from(candidate.plan_verification_receipt.content_base64, 'base64').toString('utf8')); verificationReceipt.value_preservation_plan_material_sha256 = candidate.value_preservation_plan_material.sha256; verificationReceipt.value_preservation_plan_canonical_sha256 = value.canonical_sha256; verificationReceipt.redaction_plan_material_sha256 = candidate.redaction_plan_material.sha256; verificationReceipt.redaction_plan_canonical_sha256 = redaction.canonical_sha256; verificationReceipt.source = reboundSource; candidate.plan_verification_receipt = physical('receipts/plan-verification-rebound.json', verificationReceipt); const captionTrack = JSON.parse(Buffer.from(candidate.caption_track_material.content_base64, 'base64').toString('utf8')); captionTrack.source_sha256 = reboundSource.sha256; captionTrack.canonical_sha256 = digest(Object.fromEntries(Object.entries(captionTrack).filter(([key]) => key !== 'canonical_sha256'))); candidate.caption_track_material = physical('captions/source-rebound.json', captionTrack); const captionReceipt = JSON.parse(Buffer.from(candidate.caption_verification_receipt.content_base64, 'base64').toString('utf8')); captionReceipt.source = reboundSource; captionReceipt.caption_track_material_sha256 = candidate.caption_track_material.sha256; captionReceipt.caption_track_canonical_sha256 = captionTrack.canonical_sha256; candidate.caption_verification_receipt = physical('receipts/caption-verification-rebound.json', captionReceipt); return candidate; };
  blocked('extra-field', () => assertMinimalRedactionRequest({...request, publish: true}), 'MINIMAL-REQUEST-KEYS');
  const stale = clone(request); stale.redaction_plan_material = physical('plans/stale.json', {...plan, plan_id: 'REDACTION:stale', canonical_sha256: digest({...Object.fromEntries(Object.entries(plan).filter(([key]) => key !== 'canonical_sha256')), plan_id: 'REDACTION:stale'})}); blocked('stale-receipt', () => assertMinimalRedactionRequest(stale), 'MINIMAL-VERIFICATION-DRIFT');
  const full = rebindPlan(request, (value) => { value.operations[0].signal_roi = {x: 0, y: 0, width: 320, height: 180}; value.operations[0].authorized_effect_roi = {x: 0, y: 0, width: 320, height: 180}; value.mask_budget.max_planned_ratio = 1; }); blocked('full-frame', () => assertMinimalRedactionRequest(full), 'MINIMAL-MASK-HARD-LIMIT');
  const occlusion = rebindPlan(request, (value) => { value.operations[0].signal_roi = {x: 110, y: 60, width: 10, height: 10}; value.operations[0].authorized_effect_roi = {x: 100, y: 50, width: 30, height: 30}; }); blocked('value-zone', () => assertMinimalRedactionRequest(occlusion), 'MINIMAL-VALUE-ZONE-OCCLUSION');
  const reframe = rebindPlan(request, (value) => { value.operations[0] = {...value.operations[0], type: 'REFRAME_PERIPHERAL', signal_roi: {x: 20, y: 177, width: 100, height: 3}, authorized_effect_roi: {x: 0, y: 172, width: 320, height: 8}, reframe_edge: 'BOTTOM', padding_px: 10, feather_px: 0}; }); blocked('reframe-scope', () => assertMinimalRedactionRequest(reframe), 'MINIMAL-REFRAME-TRANSFORM-SCOPE-UNDECLARED');
  const wrongFade = rebindPlan(request, (value) => { value.operations[3].fade_ms = 30; }); blocked('fade-drift', () => assertMinimalRedactionRequest(wrongFade), 'MINIMAL-AUDIO-OP');
  const lateCaption = clone(request); const lateTrack = JSON.parse(Buffer.from(lateCaption.caption_track_material.content_base64, 'base64').toString('utf8')); lateTrack.cues[0].end_ms = 2001; lateTrack.canonical_sha256 = digest(Object.fromEntries(Object.entries(lateTrack).filter(([key]) => key !== 'canonical_sha256'))); lateCaption.caption_track_material = physical('captions/late.json', lateTrack); const lateVerification = JSON.parse(Buffer.from(lateCaption.caption_verification_receipt.content_base64, 'base64').toString('utf8')); lateVerification.caption_track_material_sha256 = lateCaption.caption_track_material.sha256; lateVerification.caption_track_canonical_sha256 = lateTrack.canonical_sha256; lateCaption.caption_verification_receipt = physical('receipts/caption-verification-late.json', lateVerification); blocked('caption-duration', () => assertMinimalRedactionRequest(lateCaption), 'MINIMAL-CUE-STATE'); const forgedCaptionAuthority = clone(request); const forgedCaptionReceipt = JSON.parse(Buffer.from(forgedCaptionAuthority.caption_verification_receipt.content_base64, 'base64').toString('utf8')); forgedCaptionReceipt.actor_id = 'RT-07-H03-CAPTION-TRACK-PRODUCER'; forgedCaptionAuthority.caption_verification_receipt = physical('receipts/caption-verification-forged.json', forgedCaptionReceipt); blocked('caption-authority', () => assertMinimalRedactionRequest(forgedCaptionAuthority), 'MINIMAL-CAPTION-VERIFICATION-DRIFT');
  const relativeTool = clone(request); relativeTool.media_tool_authority.ffmpeg_path = 'ffmpeg'; blocked('path-tool', () => assertMinimalRedactionRequest(relativeTool), 'MINIMAL-TOOL-AUTHORITY');
  blocked('receipt-promotion', () => assertMinimalRedactionExecution({...receipt, maximum_state: 'READY'}), 'MINIMAL-EXECUTION-STATE');
  for (const mutate of [(value) => { value.execution_id = 'EXEC:FORGED'; }, (value) => { value.bindings.privacy_policy_sha256 = '0'.repeat(64); }, (value) => { value.toolchain.ffmpeg_sha256 = '0'.repeat(64); }, (value) => { value.toolchain.filtergraph_sha256 = '0'.repeat(64); }, (value) => { value.operations[0].signal_id = 'SIG-FORGED'; }, (value) => { value.output.sha256 = '0'.repeat(64); }, (value) => { value.captions = null; }]) { const forged = clone(receipt); mutate(forged); forged.canonical_sha256 = digest(Object.fromEntries(Object.entries(forged).filter(([key]) => key !== 'canonical_sha256'))); blocked('receipt-binding-forgery', () => assertMinimalRedactionExecution(forged, request, executionEvidence), 'MINIMAL-EXECUTION-REQUEST-DRIFT'); }
  blocked('missing-execution-evidence', () => assertMinimalRedactionExecution(receipt, request), 'MINIMAL-EXECUTION-EVIDENCE-KEYS');
  blocked('root-reuse', () => executeMinimalRedaction({...request, output_ref: 'other.mp4', caption_output_ref: 'other-captions.json', receipt_ref: 'other-receipt.json'}, {source_root: sourceRoot, output_root: sourceRoot}), 'MINIMAL-ROOT-REUSE'); const nestedOutput = resolve(sourceRoot, 'nested-output'); mkdirSync(nestedOutput); blocked('nested-output-root', () => executeMinimalRedaction({...request, output_ref: 'nested.mp4', caption_output_ref: 'nested-captions.json', receipt_ref: 'nested-receipt.json'}, {source_root: sourceRoot, output_root: nestedOutput}), 'MINIMAL-ROOT-REUSE'); blocked('nested-source-root', () => executeMinimalRedaction({...request, output_ref: 'outer.mp4', caption_output_ref: 'outer-captions.json', receipt_ref: 'outer-receipt.json'}, {source_root: sourceRoot, output_root: root}), 'MINIMAL-ROOT-REUSE'); blocked('overwrite', () => executeMinimalRedaction(request, {source_root: sourceRoot, output_root: outputRoot}), 'MINIMAL-OUTPUT-EXISTS');
  const multiPath = resolve(sourceRoot, 'multi-audio.mp4'); command(ffmpeg, ['-v', 'error', '-f', 'lavfi', '-i', 'testsrc2=size=320x180:rate=30:duration=2', '-f', 'lavfi', '-i', 'sine=frequency=880:sample_rate=48000:duration=2', '-f', 'lavfi', '-i', 'sine=frequency=440:sample_rate=48000:duration=2', '-map', '0:v:0', '-map', '1:a:0', '-map', '2:a:0', '-frames:v', '60', '-c:v', 'libx264', '-preset', 'medium', '-crf', '0', '-pix_fmt', 'yuv420p', '-c:a', 'alac', '-movflags', '+faststart', multiPath]); const multiBytes = readFileSync(multiPath); const multiRequest = rebindSource(request, {ref: 'multi-audio.mp4', sha256: sha(multiBytes), bytes: multiBytes.length}); multiRequest.output_ref = 'multi.mp4'; multiRequest.caption_output_ref = 'multi-captions.json'; multiRequest.receipt_ref = 'multi-receipt.json'; blocked('multiple-audio-streams', () => executeMinimalRedaction(multiRequest, {source_root: sourceRoot, output_root: outputRoot}), 'MINIMAL-AUDIO-STREAMS');
  const fake = resolve(root, 'fake-ffmpeg'); copyFileSync(ffmpeg, fake); const fakeTool = clone(request); fakeTool.media_tool_authority.ffmpeg_path = fake; fakeTool.media_tool_authority.ffmpeg_sha256 = '0'.repeat(64); blocked('tool-drift', () => executeMinimalRedaction({...fakeTool, output_ref: 'fake.mp4', caption_output_ref: 'fake-captions.json', receipt_ref: 'fake-receipt.json'}, {source_root: sourceRoot, output_root: outputRoot}), 'VIDEO-OS-CASE-TOOL-UNTRUSTED');
  const receiptPath = resolve(outputRoot, request.receipt_ref); const captionPath = resolve(outputRoot, request.caption_output_ref); const receiptBytes = Buffer.from(JSON.stringify(stable(receipt))); const outputBytes = readFileSync(outputPath); const captionBytes = readFileSync(captionPath); writeFileSync(outputPath, sourceBytes); const sourceSwapReceipt = clone(receipt); sourceSwapReceipt.output = {ref: request.output_ref, sha256: sha(sourceBytes), bytes: sourceBytes.length}; sourceSwapReceipt.canonical_sha256 = digest(Object.fromEntries(Object.entries(sourceSwapReceipt).filter(([key]) => key !== 'canonical_sha256'))); writeFileSync(receiptPath, JSON.stringify(stable(sourceSwapReceipt))); blocked('uncensored-source-swap', () => assertMinimalRedactionExecution(sourceSwapReceipt, request, executionEvidence), 'MINIMAL-EXECUTION-REQUEST-DRIFT'); writeFileSync(outputPath, outputBytes); writeFileSync(receiptPath, receiptBytes); writeFileSync(captionPath, sourceBytes); const captionSwapReceipt = clone(receipt); captionSwapReceipt.captions = {ref: request.caption_output_ref, sha256: sha(sourceBytes), bytes: sourceBytes.length}; captionSwapReceipt.canonical_sha256 = digest(Object.fromEntries(Object.entries(captionSwapReceipt).filter(([key]) => key !== 'canonical_sha256'))); writeFileSync(receiptPath, JSON.stringify(stable(captionSwapReceipt))); blocked('caption-arbitrary-bytes', () => assertMinimalRedactionExecution(captionSwapReceipt, request, executionEvidence), 'MINIMAL-CAPTION-MATERIAL-DRIFT'); writeFileSync(captionPath, captionBytes); writeFileSync(receiptPath, receiptBytes); writeFileSync(receiptPath, '{}'); blocked('receipt-material-drift', () => assertMinimalRedactionExecution(receipt, request, executionEvidence), 'MINIMAL-EXECUTION-RECEIPT-MATERIAL'); writeFileSync(receiptPath, receiptBytes); unlinkSync(receiptPath); symlinkSync(sourcePath, receiptPath); blocked('receipt-symlink', () => assertMinimalRedactionExecution(receipt, request, executionEvidence), 'MINIMAL-MATERIAL-TYPE'); unlinkSync(receiptPath); writeFileSync(receiptPath, receiptBytes); unlinkSync(outputPath); symlinkSync(sourcePath, outputPath); blocked('output-symlink', () => assertMinimalRedactionExecution(receipt, request, executionEvidence), 'MINIMAL-MATERIAL-TYPE');
  console.info('PASS minimal-redaction: lossless localized blur, tracked movement, stereo-safe audio/caption treatment and expanded fail-closed gates; reframe is blocked pending full transform scope.');
} finally { rmSync(root, {recursive: true, force: true}); }
