// scaffold-artifact-schemas — deterministic generator for multimedia artifact schemas.
// Source of truth: the manifest below (transcribed from _assets/artifact-registry.md table).
// Emits: _base.schema.ts (envelope) + 33 per-artifact schemas + index.ts.
// Content fields are intentionally `coverage_gap` (z.unknown()) — MIA-MEDIA-LIB-2.0.0
// field definitions are not in this repo; fabricating content fields would violate
// fail-closed. The envelope validates identity + handoff (evidence-based).

import {writeFileSync, mkdirSync} from 'node:fs';
import {join, dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import prettier from 'prettier';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Format emitted source with the repo's Prettier config so generator output is
// style-compliant and stable across re-runs (deterministic formatted output). [CONFIG]
// Config mirrors .prettierrc.json (bracketSpacing:false, printWidth:100, singleQuote:true).
const PRETTIER_CONFIG: prettier.Options = {
  arrowParens: 'always',
  bracketSpacing: false,
  singleQuote: true,
  trailingComma: 'all',
  printWidth: 100,
  parser: 'typescript',
};

function formatTs(source: string): Promise<string> {
  return prettier.format(source, PRETTIER_CONFIG);
}

function write(path: string, content: Promise<string>): Promise<void> {
  return content.then((src) => writeFileSync(path, src));
}
const OUT_DIR = join(
  __dirname,
  '..',
  '..',
  '02_proceso',
  'workflows',
  'multimedia',
  '_schema',
  'artifacts',
);

// Manifest: [artifact_id (kebab-v1), display_name, stage (P00-P09)]
// Transcribed from _assets/artifact-registry.md table (lines 11-43). [DOC]
const MANIFEST: Array<[id: string, display: string, stage: string]> = [
  ['brand-os-v1', 'Brand OS', 'P00'],
  ['calibration-sample-v1', 'Calibration sample', 'P00'],
  ['pilot-plan-v1', 'Pilot plan', 'P00'],
  ['capture-card-v1', 'Capture Card', 'P01'],
  ['triage-record-v1', 'Triage Record', 'P01'],
  ['digest-shortlist-v1', 'Digest / Shortlist', 'P01'],
  ['claim-register-v1', 'Claim Register', 'P02'],
  ['opportunity-map-v1', 'Opportunity Map', 'P02'],
  ['question-bank-v1', 'Question Bank', 'P02'],
  ['brief-campaign-map-v1', 'Brief / Campaign Map', 'P03'],
  ['ab-concepts-v1', 'A/B concepts', 'P03'],
  ['definition-of-ready-v1', 'Definition of Ready (DoR)', 'P03'],
  ['editorial-calendar-v1', 'Editorial Calendar', 'P04'],
  ['board-v1', 'Board', 'P04'],
  ['batch-plan-v1', 'Batch Plan', 'P04'],
  ['creative-spec-v1', 'Creative Specification', 'P05'],
  ['continuity-bible-v1', 'Continuity Bible', 'P05'],
  ['asset-map-v1', 'Asset Map', 'P05'],
  ['universal-prompts-v1', 'Universal prompts', 'P05'],
  ['derivatives-v1', 'Derivatives', 'P05'],
  ['asset-package-v1', 'Asset Package', 'P06'],
  ['asset-manifest-v1', 'Asset Manifest', 'P06'],
  ['capability-report-v1', 'Capability Report', 'P06'],
  ['tool-run-evidence-v1', 'Tool Run Evidence', 'P06'],
  ['review-report-v1', 'Review Report', 'P07'],
  ['verdict-v1', 'Verdict', 'P07'],
  ['top5-changes-v1', 'Top-5 changes', 'P07'],
  ['edit-candidate-v1', 'Edit Candidate', 'P08'],
  ['edl-v1', 'EDL', 'P08'],
  ['export-matrix-v1', 'Export Matrix', 'P08'],
  ['platform-package-v1', 'Platform Package', 'P09'],
  ['publication-record-v1', 'Publication Record', 'P09'],
  ['learning-report-v1', 'Learning Report', 'P09'],
];

const BASE = `// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact envelope v1 — identity + handoff contract. [DOC]
// Content fields are coverage_gap (z.unknown()): MIA-MEDIA-LIB-2.0.0 field
// definitions are not in this repo. Fabricating content would violate fail-closed.
// The envelope validates that an artifact carries the right identity for chain
// handoff (P0N.consume ⊆ P0(N-1).produce), not its creative content.
import { z } from 'zod';

export const ArtifactEnvelopeV1 = z.strictObject({
  artifact_id: z.string().min(1).max(80),
  display_name: z.string().min(1).max(120),
  schema_version: z.literal('v1'),
  stage: z.string().regex(/^P0[0-9]$/),
  producer_stage: z.string().regex(/^P0[0-9]$/).optional(),
  consumer_stage: z.array(z.string().regex(/^P0[0-9]$/)).default([]),
  required: z.boolean().default(false),
  // coverage_gap: content validation deferred to MIA-MEDIA-LIB-2.0.0 (not in repo).
  content: z.unknown().optional(),
  provenance: z
    .strictObject({
      source_hash: z.string().optional(),
      created_at: z.string().optional(),
    })
    .optional(),
});

export type ArtifactEnvelopeV1 = z.infer<typeof ArtifactEnvelopeV1>;
`;

const schemaFile = (
  id: string,
  display: string,
  stage: string,
) => `// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: ${display} (${stage}) — envelope schema. Content = coverage_gap.
import { z } from 'zod';
import { ArtifactEnvelopeV1 } from './_base.schema';

export const ${camel(id)} = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('${id}'),
  display_name: z.literal('${display.replace(/'/g, "\\'")}'),
  stage: z.literal('${stage}'),
});

export type ${camel(id)} = z.infer<typeof ${camel(id)}>;
`;

function camel(kebab: string): string {
  // brand-os-v1 -> brandOsV1
  const parts = kebab.replace(/-v[0-9]+$/, '').split('-');
  const tail = kebab.match(/-v[0-9]+$/)?.[0]?.replace(/-/g, '') ?? '';
  const c = parts.map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1))).join('');
  return c + (tail ? tail.charAt(0).toUpperCase() + tail.slice(1) : '');
}

const indexExports = MANIFEST.map(([id]) => `export * from './${id}.schema';`).join('\n');

async function main() {
  mkdirSync(OUT_DIR, {recursive: true});
  await write(join(OUT_DIR, '_base.schema.ts'), formatTs(BASE));
  for (const [id, display, stage] of MANIFEST) {
    await write(join(OUT_DIR, `${id}.schema.ts`), formatTs(schemaFile(id, display, stage)));
  }
  await write(
    join(OUT_DIR, 'index.ts'),
    formatTs(
      `// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.\nexport * from './_base.schema';\n${indexExports}\n`,
    ),
  );
  console.info(
    `scaffold-artifact-schemas: emitted ${MANIFEST.length} schemas + base + index -> ${OUT_DIR}`,
  );
}

void main();
