// scaffold-artifact-schemas — deterministic generator for multimedia artifact schemas.
// Source of truth: deliverable-definition-registry.yml. [CONFIG]
// Emits: typed envelope + one schema per definition + index + human registry.

import {writeFileSync, mkdirSync, readFileSync} from 'node:fs';
import {join, dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import prettier from 'prettier';
import {parse} from 'yaml';

import {DeliverableDefinitionRegistryV1Schema} from '../../02_proceso/workflows/multimedia/_schema/deliverable-v1.schema.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Format emitted source with the repo's Prettier config so generator output is
// style-compliant and stable across re-runs (deterministic formatted output). [CONFIG]
// Config mirrors .prettierrc.json (bracketSpacing:false, printWidth:100, singleQuote:true).
const PRETTIER_CONFIG: prettier.Options = {
  arrowParens: 'always',
  bracketSpacing: false,
  singleQuote: true,
  trailingComma: 'all',
  printWidth: 100,
  parser: 'typescript',
};

function formatTs(source: string): Promise<string> {
  return prettier.format(source, PRETTIER_CONFIG);
}

function write(path: string, content: Promise<string>): Promise<void> {
  return content.then((src) => writeFileSync(path, src));
}
const OUT_DIR = join(
  __dirname,
  '..',
  '..',
  '02_proceso',
  'workflows',
  'multimedia',
  '_schema',
  'artifacts',
);
const ASSET_DIR = join(OUT_DIR, '..', '..', '_assets');
const DEFINITIONS = DeliverableDefinitionRegistryV1Schema.parse(
  parse(readFileSync(join(ASSET_DIR, 'deliverable-definition-registry.yml'), 'utf8')),
).definitions;

const BASE = `// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact envelope v1 — identity + handoff contract. [DOC]
// Content is a strict runtime binding; editorial meaning lives in the hash-bound
// FramesDeliverableV1 Markdown/HTML pair. [CÓDIGO]
import { z } from 'zod';

export const ArtifactEnvelopeV1 = z.strictObject({
  artifact_id: z.string().min(1).max(80),
  display_name: z.string().min(1).max(120),
  schema_version: z.literal('v1'),
  stage: z.string().regex(/^P0[0-9]$/),
  producer_stage: z.string().regex(/^P0[0-9]$/).optional(),
  consumer_stage: z.array(z.string().regex(/^P0[0-9]$/)).default([]),
  required: z.boolean().default(false),
  content: z.strictObject({
    status: z.literal('RENDERED_DRAFT'),
    evidence_status: z.enum(['known', 'unknown']),
    evidence_tags: z.array(z.string().min(1)).min(1),
    template_id: z.string().regex(/^TPL-[A-Z0-9][A-Z0-9-]{2,79}$/u),
    limitation: z.string().min(1),
  }),
  provenance: z
    .strictObject({
      source_hash: z.string().optional(),
      created_at: z.string().optional(),
    })
    .optional(),
});

export type ArtifactEnvelopeV1 = z.infer<typeof ArtifactEnvelopeV1>;
`;

const schemaFile = (
  id: string,
  display: string,
  stage: string,
) => `// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: ${display} (${stage}) — typed runtime envelope.
import { z } from 'zod';
import { ArtifactEnvelopeV1 } from './_base.schema';

export const ${camel(id)} = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('${id}'),
  display_name: z.literal('${display.replace(/'/g, "\\'")}'),
  stage: z.literal('${stage}'),
});

export type ${camel(id)} = z.infer<typeof ${camel(id)}>;
`;

function camel(kebab: string): string {
  // brand-os-v1 -> brandOsV1
  const parts = kebab.replace(/-v[0-9]+$/, '').split('-');
  const tail = kebab.match(/-v[0-9]+$/)?.[0]?.replace(/-/g, '') ?? '';
  const c = parts.map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1))).join('');
  return c + (tail ? tail.charAt(0).toUpperCase() + tail.slice(1) : '');
}

const indexExports = DEFINITIONS.map(
  ({deliverable_id}) => `export * from './${deliverable_id}.schema';`,
).join('\n');

const registryMarkdown = (): string => {
  const rows = DEFINITIONS.map(
    ({workflow_id, display_name, deliverable_id, deliverable_class, touchpoint}) =>
      `| ${workflow_id} | ${display_name} | ${deliverable_class} | ${touchpoint} | \`${deliverable_id}.schema.ts\` |`,
  );
  return [
    '# Artifact Registry — Multimedia P00–P09',
    '',
    `**Fuente canónica:** \`deliverable-definition-registry.yml\`. ${DEFINITIONS.length} entregables tipados. [CONFIG]`,
    '',
    '| Etapa | Entregable | Clase | Punto de contacto | Schema |',
    '| --- | --- | --- | --- | --- |',
    ...rows,
    '',
    'Cada output resuelve una definición, un schema y un companion Markdown/HTML hash-bound. El contenido runtime es estricto; el significado editorial se valida mediante `FramesDeliverableV1`. [CÓDIGO]',
    '',
    '`RENDERED_DRAFT != HUMAN_APPROVED != READY != PUBLISHED`. [CONFIG]',
    '',
  ].join('\n');
};

async function main() {
  mkdirSync(OUT_DIR, {recursive: true});
  await write(join(OUT_DIR, '_base.schema.ts'), formatTs(BASE));
  for (const {deliverable_id, display_name, workflow_id} of DEFINITIONS) {
    await write(
      join(OUT_DIR, `${deliverable_id}.schema.ts`),
      formatTs(schemaFile(deliverable_id, display_name, workflow_id)),
    );
  }
  await write(
    join(OUT_DIR, 'index.ts'),
    formatTs(
      `// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.\nexport * from './_base.schema';\n${indexExports}\n`,
    ),
  );
  writeFileSync(join(ASSET_DIR, 'artifact-registry.md'), registryMarkdown(), 'utf8');
  console.info(
    `scaffold-artifact-schemas: emitted ${DEFINITIONS.length} schemas + base + index + registry`,
  );
}

void main();
