// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact envelope v1 — identity + handoff contract. [DOC]
// Content is a strict runtime binding; editorial meaning lives in the hash-bound
// FramesDeliverableV1 Markdown/HTML pair. [CÓDIGO]
import {z} from 'zod';

export const ArtifactEnvelopeV1 = z.strictObject({
  artifact_id: z.string().min(1).max(80),
  display_name: z.string().min(1).max(120),
  schema_version: z.literal('v1'),
  stage: z.string().regex(/^P0[0-9]$/),
  producer_stage: z
    .string()
    .regex(/^P0[0-9]$/)
    .optional(),
  consumer_stage: z.array(z.string().regex(/^P0[0-9]$/)).default([]),
  required: z.boolean().default(false),
  content: z.strictObject({
    status: z.enum(['DRAFT', 'RENDERED_DRAFT']),
    evidence_status: z.enum(['known', 'unknown']),
    evidence_tags: z.array(z.string().min(1)).min(1),
    template_id: z.string().regex(/^TPL-[A-Z0-9][A-Z0-9-]{2,79}$/u),
    limitation: z.string().min(1),
    markdown_ref: z.string().min(1),
    html_ref: z.string().min(1),
    content_sha256: z.string().regex(/^[a-f0-9]{64}$/u),
  }),
  provenance: z
    .strictObject({
      source_hash: z.string().optional(),
      created_at: z.string().optional(),
    })
    .optional(),
});

export type ArtifactEnvelopeV1 = z.infer<typeof ArtifactEnvelopeV1>;
