// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact envelope v1 — identity + handoff contract. [DOC]
// Content fields are coverage_gap (z.unknown()): MIA-MEDIA-LIB-2.0.0 field
// definitions are not in this repo. Fabricating content would violate fail-closed.
// The envelope validates that an artifact carries the right identity for chain
// handoff (P0N.consume ⊆ P0(N-1).produce), not its creative content.
import {z} from 'zod';

export const ArtifactEnvelopeV1 = z.strictObject({
  artifact_id: z.string().min(1).max(80),
  display_name: z.string().min(1).max(120),
  schema_version: z.literal('v1'),
  stage: z.string().regex(/^P0[0-9]$/),
  producer_stage: z
    .string()
    .regex(/^P0[0-9]$/)
    .optional(),
  consumer_stage: z.array(z.string().regex(/^P0[0-9]$/)).default([]),
  required: z.boolean().default(false),
  // coverage_gap: content validation deferred to MIA-MEDIA-LIB-2.0.0 (not in repo).
  content: z.unknown().optional(),
  provenance: z
    .strictObject({
      source_hash: z.string().optional(),
      created_at: z.string().optional(),
    })
    .optional(),
});

export type ArtifactEnvelopeV1 = z.infer<typeof ArtifactEnvelopeV1>;
