// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Conceptos A/B (P03) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const abConceptsV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('ab-concepts-v1'),
  display_name: z.literal('Conceptos A/B'),
  stage: z.literal('P03'),
});

export type abConceptsV1 = z.infer<typeof abConceptsV1>;
