// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Paquete de piezas candidatas (P06) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const assetPackageV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('asset-package-v1'),
  display_name: z.literal('Paquete de piezas candidatas'),
  stage: z.literal('P06'),
});

export type assetPackageV1 = z.infer<typeof assetPackageV1>;
