// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Asset Package (P06) — envelope schema. Content = coverage_gap.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const assetPackageV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('asset-package-v1'),
  display_name: z.literal('Asset Package'),
  stage: z.literal('P06'),
});

export type assetPackageV1 = z.infer<typeof assetPackageV1>;
