// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Mapa de activos (P05) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const assetMapV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('asset-map-v1'),
  display_name: z.literal('Mapa de activos'),
  stage: z.literal('P05'),
});

export type assetMapV1 = z.infer<typeof assetMapV1>;
