// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Manifiesto de activos (P06) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const assetManifestV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('asset-manifest-v1'),
  display_name: z.literal('Manifiesto de activos'),
  stage: z.literal('P06'),
});

export type assetManifestV1 = z.infer<typeof assetManifestV1>;
