// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Batch Plan (P04) — envelope schema. Content = coverage_gap.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const batchPlanV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('batch-plan-v1'),
  display_name: z.literal('Batch Plan'),
  stage: z.literal('P04'),
});

export type batchPlanV1 = z.infer<typeof batchPlanV1>;
