// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Tablero de producción (P04) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const boardV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('board-v1'),
  display_name: z.literal('Tablero de producción'),
  stage: z.literal('P04'),
});

export type boardV1 = z.infer<typeof boardV1>;
