// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Charter de marca (P00) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const brandCharterV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('brand-charter-v1'),
  display_name: z.literal('Charter de marca'),
  stage: z.literal('P00'),
});

export type brandCharterV1 = z.infer<typeof brandCharterV1>;
