// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Brand OS (P00) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const brandOsV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('brand-os-v1'),
  display_name: z.literal('Brand OS'),
  stage: z.literal('P00'),
});

export type brandOsV1 = z.infer<typeof brandOsV1>;
