// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Brief y mapa de campaña (P03) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const briefCampaignMapV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('brief-campaign-map-v1'),
  display_name: z.literal('Brief y mapa de campaña'),
  stage: z.literal('P03'),
});

export type briefCampaignMapV1 = z.infer<typeof briefCampaignMapV1>;
