// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Brief / Campaign Map (P03) — envelope schema. Content = coverage_gap.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const briefCampaignMapV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('brief-campaign-map-v1'),
  display_name: z.literal('Brief / Campaign Map'),
  stage: z.literal('P03'),
});

export type briefCampaignMapV1 = z.infer<typeof briefCampaignMapV1>;
