// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Muestra de calibración (P00) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const calibrationSampleV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('calibration-sample-v1'),
  display_name: z.literal('Muestra de calibración'),
  stage: z.literal('P00'),
});

export type calibrationSampleV1 = z.infer<typeof calibrationSampleV1>;
