// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Calibration sample (P00) — envelope schema. Content = coverage_gap.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const calibrationSampleV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('calibration-sample-v1'),
  display_name: z.literal('Calibration sample'),
  stage: z.literal('P00'),
});

export type calibrationSampleV1 = z.infer<typeof calibrationSampleV1>;
