// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Charter de campaña (P03) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const campaignCharterV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('campaign-charter-v1'),
  display_name: z.literal('Charter de campaña'),
  stage: z.literal('P03'),
});

export type campaignCharterV1 = z.infer<typeof campaignCharterV1>;
