// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Reporte de capacidad (P06) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const capabilityReportV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('capability-report-v1'),
  display_name: z.literal('Reporte de capacidad'),
  stage: z.literal('P06'),
});

export type capabilityReportV1 = z.infer<typeof capabilityReportV1>;
