// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Capability Report (P06) — envelope schema. Content = coverage_gap.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const capabilityReportV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('capability-report-v1'),
  display_name: z.literal('Capability Report'),
  stage: z.literal('P06'),
});

export type capabilityReportV1 = z.infer<typeof capabilityReportV1>;
