// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Ficha de captura (P01) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const captureCardV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('capture-card-v1'),
  display_name: z.literal('Ficha de captura'),
  stage: z.literal('P01'),
});

export type captureCardV1 = z.infer<typeof captureCardV1>;
