// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Capture Card (P01) — envelope schema. Content = coverage_gap.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const captureCardV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('capture-card-v1'),
  display_name: z.literal('Capture Card'),
  stage: z.literal('P01'),
});

export type captureCardV1 = z.infer<typeof captureCardV1>;
