// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Claim Register (P02) — envelope schema. Content = coverage_gap.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const claimRegisterV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('claim-register-v1'),
  display_name: z.literal('Claim Register'),
  stage: z.literal('P02'),
});

export type claimRegisterV1 = z.infer<typeof claimRegisterV1>;
