// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Registro de claims (P02) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const claimRegisterV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('claim-register-v1'),
  display_name: z.literal('Registro de claims'),
  stage: z.literal('P02'),
});

export type claimRegisterV1 = z.infer<typeof claimRegisterV1>;
