// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Continuity Bible (P05) — envelope schema. Content = coverage_gap.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const continuityBibleV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('continuity-bible-v1'),
  display_name: z.literal('Continuity Bible'),
  stage: z.literal('P05'),
});

export type continuityBibleV1 = z.infer<typeof continuityBibleV1>;
