// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Parrilla de contenidos (P04) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const contentGridV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('content-grid-v1'),
  display_name: z.literal('Parrilla de contenidos'),
  stage: z.literal('P04'),
});

export type contentGridV1 = z.infer<typeof contentGridV1>;
