// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Creative Specification (P05) — envelope schema. Content = coverage_gap.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const creativeSpecV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('creative-spec-v1'),
  display_name: z.literal('Creative Specification'),
  stage: z.literal('P05'),
});

export type creativeSpecV1 = z.infer<typeof creativeSpecV1>;
