// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Especificación creativa (P05) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const creativeSpecV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('creative-spec-v1'),
  display_name: z.literal('Especificación creativa'),
  stage: z.literal('P05'),
});

export type creativeSpecV1 = z.infer<typeof creativeSpecV1>;
