// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Definition of Ready (DoR) (P03) — envelope schema. Content = coverage_gap.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const definitionOfReadyV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('definition-of-ready-v1'),
  display_name: z.literal('Definition of Ready (DoR)'),
  stage: z.literal('P03'),
});

export type definitionOfReadyV1 = z.infer<typeof definitionOfReadyV1>;
