// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Sistema de derivados (P05) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const derivativesV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('derivatives-v1'),
  display_name: z.literal('Sistema de derivados'),
  stage: z.literal('P05'),
});

export type derivativesV1 = z.infer<typeof derivativesV1>;
