// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Digest / Shortlist (P01) — envelope schema. Content = coverage_gap.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const digestShortlistV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('digest-shortlist-v1'),
  display_name: z.literal('Digest / Shortlist'),
  stage: z.literal('P01'),
});

export type digestShortlistV1 = z.infer<typeof digestShortlistV1>;
