// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Digest y shortlist (P01) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const digestShortlistV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('digest-shortlist-v1'),
  display_name: z.literal('Digest y shortlist'),
  stage: z.literal('P01'),
});

export type digestShortlistV1 = z.infer<typeof digestShortlistV1>;
