// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Candidate editado (P08) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const editCandidateV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('edit-candidate-v1'),
  display_name: z.literal('Candidate editado'),
  stage: z.literal('P08'),
});

export type editCandidateV1 = z.infer<typeof editCandidateV1>;
