// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Editorial Calendar (P04) — envelope schema. Content = coverage_gap.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const editorialCalendarV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('editorial-calendar-v1'),
  display_name: z.literal('Editorial Calendar'),
  stage: z.literal('P04'),
});

export type editorialCalendarV1 = z.infer<typeof editorialCalendarV1>;
