// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Cronograma editorial (P04) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const editorialCalendarV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('editorial-calendar-v1'),
  display_name: z.literal('Cronograma editorial'),
  stage: z.literal('P04'),
});

export type editorialCalendarV1 = z.infer<typeof editorialCalendarV1>;
