// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: EDL (P08) — envelope schema. Content = coverage_gap.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const edlV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('edl-v1'),
  display_name: z.literal('EDL'),
  stage: z.literal('P08'),
});

export type edlV1 = z.infer<typeof edlV1>;
