// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Lista de decisiones de edición (P08) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const edlV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('edl-v1'),
  display_name: z.literal('Lista de decisiones de edición'),
  stage: z.literal('P08'),
});

export type edlV1 = z.infer<typeof edlV1>;
