// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Export Matrix (P08) — envelope schema. Content = coverage_gap.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const exportMatrixV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('export-matrix-v1'),
  display_name: z.literal('Export Matrix'),
  stage: z.literal('P08'),
});

export type exportMatrixV1 = z.infer<typeof exportMatrixV1>;
