// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Learning Report (P09) — envelope schema. Content = coverage_gap.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const learningReportV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('learning-report-v1'),
  display_name: z.literal('Learning Report'),
  stage: z.literal('P09'),
});

export type learningReportV1 = z.infer<typeof learningReportV1>;
