// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Mapa de oportunidades (P02) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const opportunityMapV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('opportunity-map-v1'),
  display_name: z.literal('Mapa de oportunidades'),
  stage: z.literal('P02'),
});

export type opportunityMapV1 = z.infer<typeof opportunityMapV1>;
