// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Ficha de familia de pieza (P05) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const pieceFamilySpecV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('piece-family-spec-v1'),
  display_name: z.literal('Ficha de familia de pieza'),
  stage: z.literal('P05'),
});

export type pieceFamilySpecV1 = z.infer<typeof pieceFamilySpecV1>;
