// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Plan piloto (P00) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const pilotPlanV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('pilot-plan-v1'),
  display_name: z.literal('Plan piloto'),
  stage: z.literal('P00'),
});

export type pilotPlanV1 = z.infer<typeof pilotPlanV1>;
