// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Pilot plan (P00) — envelope schema. Content = coverage_gap.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const pilotPlanV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('pilot-plan-v1'),
  display_name: z.literal('Pilot plan'),
  stage: z.literal('P00'),
});

export type pilotPlanV1 = z.infer<typeof pilotPlanV1>;
