// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Platform Package (P09) — envelope schema. Content = coverage_gap.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const platformPackageV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('platform-package-v1'),
  display_name: z.literal('Platform Package'),
  stage: z.literal('P09'),
});

export type platformPackageV1 = z.infer<typeof platformPackageV1>;
