// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Paquete por plataforma (P09) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const platformPackageV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('platform-package-v1'),
  display_name: z.literal('Paquete por plataforma'),
  stage: z.literal('P09'),
});

export type platformPackageV1 = z.infer<typeof platformPackageV1>;
