// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Publication Record (P09) — envelope schema. Content = coverage_gap.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const publicationRecordV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('publication-record-v1'),
  display_name: z.literal('Publication Record'),
  stage: z.literal('P09'),
});

export type publicationRecordV1 = z.infer<typeof publicationRecordV1>;
