// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Banco de preguntas (P02) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const questionBankV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('question-bank-v1'),
  display_name: z.literal('Banco de preguntas'),
  stage: z.literal('P02'),
});

export type questionBankV1 = z.infer<typeof questionBankV1>;
