// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Question Bank (P02) — envelope schema. Content = coverage_gap.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const questionBankV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('question-bank-v1'),
  display_name: z.literal('Question Bank'),
  stage: z.literal('P02'),
});

export type questionBankV1 = z.infer<typeof questionBankV1>;
