// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Review Report (P07) — envelope schema. Content = coverage_gap.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const reviewReportV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('review-report-v1'),
  display_name: z.literal('Review Report'),
  stage: z.literal('P07'),
});

export type reviewReportV1 = z.infer<typeof reviewReportV1>;
