// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Tool Run Evidence (P06) — envelope schema. Content = coverage_gap.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const toolRunEvidenceV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('tool-run-evidence-v1'),
  display_name: z.literal('Tool Run Evidence'),
  stage: z.literal('P06'),
});

export type toolRunEvidenceV1 = z.infer<typeof toolRunEvidenceV1>;
