// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Evidencia de ejecución (P06) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const toolRunEvidenceV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('tool-run-evidence-v1'),
  display_name: z.literal('Evidencia de ejecución'),
  stage: z.literal('P06'),
});

export type toolRunEvidenceV1 = z.infer<typeof toolRunEvidenceV1>;
