// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Cambios prioritarios (P07) — typed runtime envelope.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const top5ChangesV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('top5-changes-v1'),
  display_name: z.literal('Cambios prioritarios'),
  stage: z.literal('P07'),
});

export type top5ChangesV1 = z.infer<typeof top5ChangesV1>;
