// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Triage Record (P01) — envelope schema. Content = coverage_gap.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const triageRecordV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('triage-record-v1'),
  display_name: z.literal('Triage Record'),
  stage: z.literal('P01'),
});

export type triageRecordV1 = z.infer<typeof triageRecordV1>;
