// AUTO-GENERATED by scaffold-artifact-schemas.ts — do not edit by hand.
// Artifact: Verdict (P07) — envelope schema. Content = coverage_gap.
import {z} from 'zod';
import {ArtifactEnvelopeV1} from './_base.schema';

export const verdictV1 = ArtifactEnvelopeV1.extend({
  artifact_id: z.literal('verdict-v1'),
  display_name: z.literal('Verdict'),
  stage: z.literal('P07'),
});

export type verdictV1 = z.infer<typeof verdictV1>;
